//
//  ChargebackModels.swift
//  Chargebacker
//
//  Created by Lucas Pereira on 24/06/17.
//  Copyright (c) 2017 Lucas Pereira. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Chargeback {

    public enum ReasonId: String {
        case merchant_recognized
        case card_in_possession
    }
    
    enum Data {
        
        struct Request {
            let comment: String
            var reasonDetails: [ReasonDetail]
            var input: ChargebackInput {
                return ChargebackInput(comment: comment,
                                       reasonDetails: reasonDetails)
            }
            
            init(comment: String) {
                self.comment = comment
                self.reasonDetails = [ReasonDetail]()
            }
            
            mutating func addReason(id: ReasonId, response: Bool) {
                reasonDetails.append(ReasonDetail(id: id.rawValue,
                                                  title: "",
                                                  response: response))
            }
        }
        
        struct ViewModel {
            let title: String
            let hint: String
            let autoblock: Bool
            let merchantRecognizedReason: ReasonDetail
            let cardInPossessionReason: ReasonDetail
        }
    }
}
