//
//  ChargebackPresenter.swift
//  Chargebacker
//
//  Created by Lucas Pereira on 24/06/17.
//  Copyright (c) 2017 Lucas Pereira. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChargebackPresentationLogic {
    func handleCard(blocked: Bool)
    func handleContest(succeeded: Bool, errorMessage: String?)
}

class ChargebackPresenter: ChargebackPresentationLogic {
    
    weak var viewController: ChargebackDisplayLogic?
    
    func handleCard(blocked: Bool) {
        viewController?.cardStateUpdated(blocked: blocked)
    }
    
    func handleContest(succeeded: Bool, errorMessage: String?) {
        if succeeded {
            viewController?.contestSucceeded()
        } else {
            viewController?.contestFailed(errorMessage: errorMessage)
        }
    }
}
