//
//  ChargebackInteractor.swift
//  Chargebacker
//
//  Created by Lucas Pereira on 24/06/17.
//  Copyright (c) 2017 Lucas Pereira. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChargebackBusinessLogic
{
    func setCard(blocked: Bool, showSpinner: Bool)
    func tappedContest(request: Chargeback.Data.Request)
}

protocol ChargebackDataStore
{
}

class ChargebackInteractor: ChargebackBusinessLogic, ChargebackDataStore
{
    var presenter: ChargebackPresentationLogic?
    var worker: ChargebackWorker?
    
    // MARK: Do something
    
    func setCard(blocked: Bool, showSpinner: Bool)
    {
        API.Card.setCard(blocked: blocked, showSpinner: showSpinner) { [weak self] succeeded, errorMessage in
            guard succeeded else {
                GeneralAlerter.displayErrorAlert(message: errorMessage)
                return
            }
            self?.presenter?.handleCard(blocked: blocked)
        }
    }
    
    func tappedContest(request: Chargeback.Data.Request) {
        
        API.Chargeback.performChargebackOperation(input: request.input) { [weak self] succeeded, errorMessage in
            self?.presenter?.handleContest(succeeded: succeeded, errorMessage: errorMessage)
        }
    }
}
