//
//  NoticePresenter.swift
//  Chargebacker
//
//  Created by Lucas Pereira on 24/06/17.
//  Copyright (c) 2017 Lucas Pereira. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NoticePresentationLogic
{
    func presentNoticeData(response: Notice.Data.Response)
    func proceedToChargebackScene(viewModel: Chargeback.Data.ViewModel)
}

class NoticePresenter: NoticePresentationLogic
{
    weak var viewController: NoticeDisplayLogic?
    
    func presentNoticeData(response: Notice.Data.Response)
    {
        let output = response.output
        let viewModel = Notice.Data.ViewModel(title: output.title,
                                              description: output.description,
                                              primaryAction: output.primaryAction,
                                              secondaryAction: output.secondaryAction)
        
        viewController?.displayData(viewModel: viewModel)
    }
    
    func proceedToChargebackScene(viewModel: Chargeback.Data.ViewModel) {
        viewController?.proceedToChargebackScene(viewModel: viewModel)
    }
}
