//
//  NoticeModels.swift
//  Chargebacker
//
//  Created by Lucas Pereira on 24/06/17.
//  Copyright (c) 2017 Lucas Pereira. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Notice {
    
    enum Data {
        
        struct Response {
            let output: NoticeOutput
        }
        
        struct ViewModel {
            let title: String
            let description: String
            let primaryAction: NoticeOutput.Action
            let secondaryAction: NoticeOutput.Action
        }
    }
}
