//
//  NoticeInteractor.swift
//  Chargebacker
//
//  Created by Lucas Pereira on 24/06/17.
//  Copyright (c) 2017 Lucas Pereira. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import ALLoadingView

protocol NoticeBusinessLogic
{
    func fetchData()
    func handlePrimaryAction()
}

class NoticeInteractor: NoticeBusinessLogic {
    var presenter: NoticePresentationLogic?
    
    func fetchData() {
        ALLoadingView.show()
        API.Notice.getData { [weak self] output, errorMessage in
            ALLoadingView.hide()
            guard let output = output else {
                GeneralAlerter.displayErrorAlert(message: errorMessage)
                return
            }
            let response = Notice.Data.Response(output: output)
            self?.presenter?.presentNoticeData(response: response)
        }
    }
    
    func handlePrimaryAction() {
        ALLoadingView.show()
        API.Chargeback.getData { [weak self] output, errorMessage in
            ALLoadingView.hide()
            guard let output = output else {
                GeneralAlerter.displayErrorAlert(message: errorMessage)
                return
            }
            
            let worker = NoticeWorker(output: output)
            
            guard let merchantRecognized = worker.getReason(id: .merchant_recognized),
                let cardInPossession = worker.getReason(id: .card_in_possession) else {
                    GeneralAlerter.displayErrorAlert(message: errorMessage)
                    return
            }
            
            let viewModel = Chargeback.Data.ViewModel(title: output.title,
                                                      hint: output.commentHint,
                                                      autoblock: output.autoblock,
                                                      merchantRecognizedReason: merchantRecognized,
                                                      cardInPossessionReason: cardInPossession)
            self?.presenter?.proceedToChargebackScene(viewModel: viewModel)
        }
    }
}
